language: python

python:
 - "2.7"

services: postgresql

before_install:
 - export DJANGO_SETTINGS_MODULE=website.settings.test
 - export PYTHONPATH=$HOME/builds/rapidsms/rapidsms.org

install:
 - pip install -r requirements/base.txt --use-mirrors

script:
 - python manage.py test packages projects users
