language: python

python:
 - "2.7"

services: postgresql

before_install:
 - export DJANGO_SETTINGS_MODULE=website.settings.test
 - export PYTHONPATH=$HOME/builds/rapidsms/rapidsms.org

install:
 - pip install -r requirements/base.txt --use-mirrors

before_script:
 - psql -c "CREATE_DATABASE test_rapidsms_website;" -U postgres
 - python manage.py syncdb --migrate

script:
 - python manage.py test packages projects users
